import type { Metadata } from "next";

export const metadata: Metadata = { title: "Terms of Service — NomNate" };

export default function TermsOfService() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-slate text-sm">Last updated: 10 May 2026</p>

      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your use of NomNate (&ldquo;the Service&rdquo;).
        By creating an account you agree to these Terms. If you do not agree, do not use the Service.
      </p>

      <h2>1. The Service</h2>
      <p>
        NomNate is a family meal-planning application that helps households plan weekly dinners,
        vote on meal options, generate AI-powered recipe suggestions, and create store-specific
        shopping lists. The Service is operated from South Africa and is governed by South African law.
      </p>

      <h2>2. Accounts</h2>
      <ul>
        <li>You must provide a valid email address and keep your account credentials secure.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>You must be 18 years or older to create an account.</li>
        <li>One account per person. You may belong to one family group at a time.</li>
      </ul>

      <h2>3. Free tier and Premium</h2>
      <p>NomNate offers a free tier and a paid Premium tier:</p>
      <ul>
        <li>
          <strong>Free</strong> — includes family meal planning, recipe library, voting, shopping
          lists, and up to <strong>7 AI meal suggestions per week</strong>.
        </li>
        <li>
          <strong>Premium (R79/month)</strong> — unlimited AI suggestions, priority support, and
          additional features as they are released.
        </li>
        <li>
          <strong>Family Bundle (R129/month)</strong> — Premium features across your entire family
          group.
        </li>
      </ul>
      <p>
        Premium subscriptions are billed monthly via PayFast. You may cancel at any time; access
        continues until the end of the current billing period. We reserve the right to change
        pricing with 30 days&apos; notice.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose.</li>
        <li>Attempt to reverse-engineer, scrape, or abuse the AI suggestion feature.</li>
        <li>Submit content that is abusive, defamatory, or infringes third-party rights.</li>
        <li>Share your account with others outside your family group.</li>
        <li>Circumvent free-tier limits through multiple accounts.</li>
      </ul>

      <h2>5. Content you submit</h2>
      <p>
        You retain ownership of content you submit (recipes, feedback, preferences). By submitting
        content, you grant NomNate a non-exclusive licence to store and display that content to
        provide the Service to your family group. We do not sell your content or use it for
        advertising.
      </p>

      <h2>6. AI-generated content</h2>
      <p>
        AI meal suggestions are generated by Anthropic&apos;s Claude and are provided as inspiration
        only. We make no warranties about their accuracy, nutritional completeness, or suitability
        for specific medical dietary needs. Always consult a healthcare professional for medically
        necessary dietary requirements.
      </p>

      <h2>7. Service availability</h2>
      <p>
        We aim for high availability but do not guarantee uninterrupted service. We may perform
        maintenance, updates, or changes at any time. We are not liable for any loss arising from
        temporary unavailability.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by South African law, NomNate is not liable for indirect,
        incidental, or consequential damages arising from your use of the Service. Our total
        liability to you will not exceed the amount you paid to us in the 12 months preceding
        the claim.
      </p>

      <h2>9. Termination</h2>
      <p>
        You may delete your account at any time from your profile settings. We may suspend or
        terminate accounts that violate these Terms. On termination, your data will be deleted
        in accordance with our <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>10. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. We will notify you of material changes via
        email at least 14 days before they take effect. Continued use of the Service after that
        date constitutes acceptance of the new Terms.
      </p>

      <h2>11. Governing law</h2>
      <p>
        These Terms are governed by the laws of the Republic of South Africa. Any disputes will
        be resolved in the courts of South Africa.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these Terms? Email{" "}
        <a href="mailto:legal@nomnate.co.za">legal@nomnate.co.za</a>.
      </p>
    </>
  );
}
